#!/usr/bin/env bash

# $1 github organization
# $2 github repo
# $3 input file
# $4 output file

echo "Fix Elm Native Function Names: ${1}\$${2} $3 -> $4"
cat $3 | sed "s/_yjpark\$elm_yjpark_util\$Native/_${1}\$${2}\$Native/g" > $4
